### ISSUE TITLE
Matrix application with descending Y axis

### ISSUE THREAD

**Issue by IGOR-06** [rougier/windmap#1]
How to make this animation if the matrix has decreasing Y axis?

When I tried the "while not" it creates an infinite loop.

**Comment by rougier** [comment]
Which matrix exactly?

**Comment by IGOR-06** [comment]
For example, the Y and X are:
Y , X  =  np . mgrid [3:-3:-100j ,-3:3:100j]

**Comment by rougier** [comment]
In that case, it may be easier to stick to -3 to 3 and then you can invert the y-axis on the plot (e.g. `set_ylim(1,-1)`)

**Comment by IGOR-06** [comment]
Thank you for your help.
In fact, I managed to plot correctly by inverting the values of Y, U and V.
Y, X = Y[::-1], X
U, V = U[::-1], V[::-1]
